#!/usr/bin/python3
#-------------------------------------------------------------------------------
# WowTools Shell
#
# Christophe Cremy, May 2020
#-------------------------------------------------------------------------------

import argparse
import cmd
import sys

from modules import wow_net as wnet

#
# Globals
#

gVersion = "v0.1.a, 23 May 2020"
gSupportedvariables = {
    "ipv4" : "WowIPv4Address"
}


#
# Classes
#

class WowShell(cmd.Cmd):
    variables = {}
    prompt = "wowsh> "
    intro  = " _    _               _____ _          _ _\n"
    intro += "| |  | |             /  ___| |        | | |\n"
    intro += "| |  | | _____      _\ `--.| |__   ___| | |\n"
    intro += "| |/\| |/ _ \ \ /\ / /`--. \ '_ \ / _ \ | |\n"
    intro += "\  /\  / (_) \ V  V //\__/ / | | |  __/ | |\n"
    intro += " \/  \/ \___/ \_/\_/ \____/|_| |_|\___|_|_|\n"
    intro += "\n"
    intro += "WowShell " + gVersion + "\n"
    intro += "----\n"

    def do_exit(self, inp):
        print("WowShell tells you Bye!")
        return True
 
    def default(self, text):
        operation = text.split()[0]
        print(f"operation -> {operation}")
        print(f"text -> {text}")
        try:
            getattr(self, operation)(text)
        except Exception:
            print(f"Unsupported operation '{operation}'")

    def do_set(self, text):
        args = text.split()
        if len(args) != 2:
            print(f"Syntax error: set <variable_name> <variable_value>")
            return

        variable_name = args[0]
        if not variable_name in gSupportedvariables:
            print(f"Unsupported variable name '{variable_name}")
            return            

        variable_value = args[1]
        variable_object = getattr(wnet, gSupportedvariables[variable_name])(value = str(variable_value))
        self.variables[variable_name] = {
            "value" : variable_value,
            "object" : variable_object
        }

    def do_show(self, arg):
        if arg in self.variables:
            self.variables[arg]["object"].show()
        else:
            print(f"Unknown variable '{arg}'")

    do_EOF = do_exit


#
# Main
# 

sys.path.append(".")
sys.path.append("modules")

if __name__ == '__main__':
    WowShell().cmdloop()
